executorApiConnection:
  armadaUrl: "localhost:50052"
  forceNoTls: true
  openIdClientCredentialsAuth:
    providerUrl: "http://localhost:8180/realms/armada"
    clientId: "armada-executor"
    clientSecret: "executor-secret"
    scopes: ["profile", "email"]
