## POST /v1/job/reprioritize
## Submit a low-priority job, reprioritize it upward, confirm a JobReprioritizedEvent fires
## 1x5

numBatches: 1
batchSize: 5
queue: e2e-test-queue
jobSetId: reprioritize_by_id
jobs:
  - namespace: default
    priority: 0
    podSpec:
      terminationGracePeriodSeconds: 0
      restartPolicy: Never
      containers:
        - name: reprioritize-by-id
          imagePullPolicy: IfNotPresent
          image: alpine:3.20.0
          args:
            - "sleep"
            - "600s"
          resources:
            limits:
              memory: 25Mi
              cpu: 100m
            requests:
              memory: 25Mi
              cpu: 100m
---
### Reprioritize the job upward
reprioritize:
  request:
    newPriority: 100
timeout: "100s"
expectedEvents:
  - submitted:
  - reprioritized: