# RBAC: a principal without the global submit_any_jobs permission can submit jobs
# in a queue it has the submit permission.
queue: rbac-queue-submit
authContext: rbac-queue-only
numBatches: 1
batchSize: 1
jobs:
  - priority: 0
    namespace: personal-anonymous
    podSpec:
      terminationGracePeriodSeconds: 0
      restartPolicy: Never
      containers:
        - name: sleep
          imagePullPolicy: IfNotPresent
          image: alpine:3.20.0
          args:
            - "ls"
          resources:
            limits:
              memory: 25Mi
              cpu: 100m
            requests:
              memory: 25Mi
              cpu: 100m
---
timeout: "30s"
expectedEvents:
  - submitted:
  - succeeded:
queueConfig:
  setup:
    queueSpec:
      userOwners: ["nobody"]
      permissions:
        - subjects:
            - kind: Group
              name: queue-only
          verbs:
            - submit
            - watch
