image:
  repository: gresearch/event-ingester-ingester
  tag: latest
resources:
  limits:
    memory: 1Gi
    cpu: 300m
  requests:
    memory: 512Mi
    cpu: 200m
# -- Tolerations
tolerations: []
additionalLabels: {}
additionalVolumeMounts: []
additionalVolumes: []
terminationGracePeriodSeconds: 30
topologyKey: kubernetes.io/hostname
replicas: 1
strategy:
  rollingUpdate:
    maxUnavailable: 1
  type: RollingUpdate
customServiceAccount: null
serviceAccount: null

applicationConfig:
  pulsar:
    authenticationEnabled: false
  batchSize: 1048576  #1MB
  batchMessages: 10000
  metricsPort: 9000
  # Configuration for metrics collection.
  # If metrics.redis.enabled=true, a separate client will be used for scanning keys.
  # Sentinel mode is triggered if connectionInfo.masterName is set.
  metrics:
    redis:
      enabled: true
      connectionInfo:
        # For Sentinel mode, provide sentinel addresses and masterName.
        # readOnly must be true for metrics collection from replicas.
        # masterName: "mymaster"
        # readOnly: true
        addrs:
          - localhost:6379
        db: 1

prometheus:
  enabled: false
  labels: {}
  scrapeInterval: 15s
  scrapeTimeout: 10s
