server: ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-server ./cmd/server/main.go && ./dist/armada-server --config ./_local/server/config.yaml
scheduler: ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-scheduler ./cmd/scheduler/main.go && ./dist/armada-scheduler run --config ./cmd/regatta/config/armada/scheduler/config-regatta.yaml
scheduleringester: ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-scheduleringester ./cmd/scheduleringester/main.go && ./dist/armada-scheduleringester --config ./_local/scheduleringester/config.yaml
eventingester: ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-eventingester ./cmd/eventingester/main.go && ./dist/armada-eventingester --config ./_local/eventingester/config.yaml
executor: export KUBECONFIG=.kube/external/regatta/regatta-1 && ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-executor ./cmd/executor/main.go && ./dist/armada-executor --config ./cmd/regatta/config/armada/executor/ten-cluster/config-regatta-1.yaml
executor2: export KUBECONFIG=.kube/external/regatta/regatta-2 && ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-executor2 ./cmd/executor/main.go && ./dist/armada-executor2 --config ./cmd/regatta/config/armada/executor/ten-cluster/config-regatta-2.yaml
executor3: export KUBECONFIG=.kube/external/regatta/regatta-3 && ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-executor3 ./cmd/executor/main.go && ./dist/armada-executor3 --config ./cmd/regatta/config/armada/executor/ten-cluster/config-regatta-3.yaml
executor4: export KUBECONFIG=.kube/external/regatta/regatta-4 && ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-executor4 ./cmd/executor/main.go && ./dist/armada-executor4 --config ./cmd/regatta/config/armada/executor/ten-cluster/config-regatta-4.yaml
executor5: export KUBECONFIG=.kube/external/regatta/regatta-5 && ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-executor5 ./cmd/executor/main.go && ./dist/armada-executor5 --config ./cmd/regatta/config/armada/executor/ten-cluster/config-regatta-5.yaml
executor6: export KUBECONFIG=.kube/external/regatta/regatta-6 && ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-executor6 ./cmd/executor/main.go && ./dist/armada-executor6 --config ./cmd/regatta/config/armada/executor/ten-cluster/config-regatta-6.yaml
executor7: export KUBECONFIG=.kube/external/regatta/regatta-7 && ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-executor7 ./cmd/executor/main.go && ./dist/armada-executor7 --config ./cmd/regatta/config/armada/executor/ten-cluster/config-regatta-7.yaml
executor8: export KUBECONFIG=.kube/external/regatta/regatta-8 && ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-executor8 ./cmd/executor/main.go && ./dist/armada-executor8 --config ./cmd/regatta/config/armada/executor/ten-cluster/config-regatta-8.yaml
executor9: export KUBECONFIG=.kube/external/regatta/regatta-9 && ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-executor9 ./cmd/executor/main.go && ./dist/armada-executor9 --config ./cmd/regatta/config/armada/executor/ten-cluster/config-regatta-9.yaml
executor10: export KUBECONFIG=.kube/external/regatta/regatta-10 && ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-executor10 ./cmd/executor/main.go && ./dist/armada-executor10 --config ./cmd/regatta/config/armada/executor/ten-cluster/config-regatta-10.yaml
lookout: ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-lookout ./cmd/lookout/main.go && ./dist/armada-lookout --config ./_local/lookout/config.yaml
lookoutingester: ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-lookoutingester ./cmd/lookoutingester/main.go && ./dist/armada-lookoutingester --config ./_local/lookoutingester/config.yaml
binoculars: ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-binoculars ./cmd/binoculars/main.go && ./dist/armada-binoculars --config ./_local/binoculars/config.yaml
lookoutui: sh -c 'cd internal/lookoutui && yarn install && yarn run openapi && PROXY_TARGET=http://localhost:8089 yarn dev'
