## POST /v1/job/reprioritise
## Reprioritise an entire job set and confirm all jobs receive the update.
## 1x1
numBatches: 1
batchSize: 1
queue: e2e-test-queue
jobs:
  - priority: 0
    namespace: default
    podSpec:
      terminationGracePeriodSeconds: 0
      restartPolicy: Never
      containers:
        - name: reprioritise-by-jobset
          imagePullPolicy: IfNotPresent
          image: alpine:3.20.0
          args:
            - "sleep"
            - "100s"
          resources:
            limits:
              memory: 25Mi
              cpu: 100m
            requests:
              memory: 25Mi
              cpu: 100m
---
## Reprioritise the job set upward
triggerEvent: running
reprioritise:
  byJobSet: true
  request:
    newPriority: 100
timeout: "100s"
expectedEvents:
  - submitted:
  - reprioritised:

