merge_protections:
  # Migrated from post_check rule 'Require approval from frontend or Armada maintainers for Lookout UI changes'. Dropped options with no equivalent: title
  - name: Require approval from frontend or Armada maintainers for Lookout UI changes
    if:
      - "#approved-reviews-by>=1"
    success_conditions:
      - or:
          - "-files~=^internal/lookoutui/"
          - "#approved-reviews-by>=2"
          - and:
              - "#approved-reviews-by>=1"
              - "author~=^(d80tb7|dave[-]gantenbein|dejanzele|eleanorpratt|geaere|JamesMurkin|mauriceyap|masipauskas|MustafaI|zuqq|richscott|robertdavidsmith|samclark|suprjinx|EnricoMi|nikola-jokic|dslear|d2burkhalter|ianhockett|Sigele|williamvega|tgucks|YHines004|j8169)$"
  # Migrated from post_check rule 'Require approval from Armada maintainers'. Dropped options with no equivalent: title
  - name: Require approval from Armada maintainers
    if:
      - "#approved-reviews-by>=1"
    success_conditions:
      - or:
          - and:
              - "files~=^internal/lookoutui/"
              - "-files~=^(?!internal/lookoutui/).*$"
          - "#approved-reviews-by>=2"
          - and:
              - "#approved-reviews-by>=1"
              - "author~=^(d80tb7|dave[-]gantenbein|dejanzele|eleanorpratt|geaere|JamesMurkin|mauriceyap|masipauskas|MustafaI|zuqq|richscott|robertdavidsmith|samclark|suprjinx|EnricoMi|nikola-jokic|j8169|sarhiri)$"
