<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>

    <IsPackable>false</IsPackable>

    <RootNamespace>ArmadaProject.Io.Client.Test</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="nunit" Version="4.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="RichardSzalay.MockHttp" Version="7.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ArmadaProject.Io.Client\ArmadaProject.Io.Client.csproj" />
  </ItemGroup>

</Project>
