numBatches: 1
batchSize: 10
queue: e2e-test-queue
jobSetId: node-cancel-test
jobs:
  - priority: 0
    namespace: personal-anonymous
    podSpec:
      terminationGracePeriodSeconds: 0
      restartPolicy: Never
      nodeSelector:
        armadaproject.io/node-pool: node-ops
      tolerations:
        - key: node-tests
          operator: Equal
          value: "true"
          effect: NoSchedule
      containers:
        - name: cancel-by-node
          imagePullPolicy: IfNotPresent
          image: alpine:3.20.0
          args:
            - "sleep"
            - "90s"
          resources:
            limits:
              memory: 25Mi
              cpu: 10m
            requests:
              memory: 25Mi
              cpu: 10m
---
action: ACTION_CANCEL
selection: SELECTION_BY_NODE
nodePoolTag: node-ops
executor: local-cluster
timeout: "180s"
expectedEvents:
  - submitted:
  - cancelled:
