// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/api/interactive.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ExecRequest is sent by armadactl to the server.
type ExecRequest struct {
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecRequest_Init
	//	*ExecRequest_Stdin
	//	*ExecRequest_Resize
	Payload isExecRequest_Payload `protobuf_oneof:"payload"`
}

func (m *ExecRequest) Reset()         { *m = ExecRequest{} }
func (m *ExecRequest) String() string { return proto.CompactTextString(m) }
func (*ExecRequest) ProtoMessage()    {}
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_72adf7ebfea3b2f6, []int{0}
}
func (m *ExecRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExecRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExecRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ExecRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecRequest.Merge(m, src)
}
func (m *ExecRequest) XXX_Size() int {
	return m.Size()
}
func (m *ExecRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecRequest proto.InternalMessageInfo

type isExecRequest_Payload interface {
	isExecRequest_Payload()
	MarshalTo([]byte) (int, error)
	Size() int
}

type ExecRequest_Init struct {
	Init *ExecInit `protobuf:"bytes,1,opt,name=init,proto3,oneof" json:"init,omitempty"`
}
type ExecRequest_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof" json:"stdin,omitempty"`
}
type ExecRequest_Resize struct {
	Resize *ExecResize `protobuf:"bytes,3,opt,name=resize,proto3,oneof" json:"resize,omitempty"`
}

func (*ExecRequest_Init) isExecRequest_Payload()   {}
func (*ExecRequest_Stdin) isExecRequest_Payload()  {}
func (*ExecRequest_Resize) isExecRequest_Payload() {}

func (m *ExecRequest) GetPayload() isExecRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ExecRequest) GetInit() *ExecInit {
	if x, ok := m.GetPayload().(*ExecRequest_Init); ok {
		return x.Init
	}
	return nil
}

func (m *ExecRequest) GetStdin() []byte {
	if x, ok := m.GetPayload().(*ExecRequest_Stdin); ok {
		return x.Stdin
	}
	return nil
}

func (m *ExecRequest) GetResize() *ExecResize {
	if x, ok := m.GetPayload().(*ExecRequest_Resize); ok {
		return x.Resize
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ExecRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ExecRequest_Init)(nil),
		(*ExecRequest_Stdin)(nil),
		(*ExecRequest_Resize)(nil),
	}
}

// ExecInit is the first message sent by the client to initiate an exec session.
type ExecInit struct {
	JobId     string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"jobId,omitempty"`
	RunId     string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"runId,omitempty"`
	PodNumber int32  `protobuf:"varint,3,opt,name=pod_number,json=podNumber,proto3" json:"podNumber,omitempty"`
	// container is the target container name; empty means the default container.
	Container string   `protobuf:"bytes,4,opt,name=container,proto3" json:"container,omitempty"`
	Command   []string `protobuf:"bytes,5,rep,name=command,proto3" json:"command,omitempty"`
	Tty       bool     `protobuf:"varint,6,opt,name=tty,proto3" json:"tty,omitempty"`
	Stdin     bool     `protobuf:"varint,7,opt,name=stdin,proto3" json:"stdin,omitempty"`
}

func (m *ExecInit) Reset()         { *m = ExecInit{} }
func (m *ExecInit) String() string { return proto.CompactTextString(m) }
func (*ExecInit) ProtoMessage()    {}
func (*ExecInit) Descriptor() ([]byte, []int) {
	return fileDescriptor_72adf7ebfea3b2f6, []int{1}
}
func (m *ExecInit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExecInit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExecInit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ExecInit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecInit.Merge(m, src)
}
func (m *ExecInit) XXX_Size() int {
	return m.Size()
}
func (m *ExecInit) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecInit.DiscardUnknown(m)
}

var xxx_messageInfo_ExecInit proto.InternalMessageInfo

func (m *ExecInit) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ExecInit) GetRunId() string {
	if m != nil {
		return m.RunId
	}
	return ""
}

func (m *ExecInit) GetPodNumber() int32 {
	if m != nil {
		return m.PodNumber
	}
	return 0
}

func (m *ExecInit) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *ExecInit) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *ExecInit) GetTty() bool {
	if m != nil {
		return m.Tty
	}
	return false
}

func (m *ExecInit) GetStdin() bool {
	if m != nil {
		return m.Stdin
	}
	return false
}

// ExecResize carries terminal window size changes.
type ExecResize struct {
	Width  uint32 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height uint32 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *ExecResize) Reset()         { *m = ExecResize{} }
func (m *ExecResize) String() string { return proto.CompactTextString(m) }
func (*ExecResize) ProtoMessage()    {}
func (*ExecResize) Descriptor() ([]byte, []int) {
	return fileDescriptor_72adf7ebfea3b2f6, []int{2}
}
func (m *ExecResize) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExecResize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExecResize.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ExecResize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecResize.Merge(m, src)
}
func (m *ExecResize) XXX_Size() int {
	return m.Size()
}
func (m *ExecResize) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecResize.DiscardUnknown(m)
}

var xxx_messageInfo_ExecResize proto.InternalMessageInfo

func (m *ExecResize) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *ExecResize) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

// ExecResponse is sent by the server to armadactl.
type ExecResponse struct {
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecResponse_Stdout
	//	*ExecResponse_Stderr
	//	*ExecResponse_ExitCode
	//	*ExecResponse_Error
	Payload isExecResponse_Payload `protobuf_oneof:"payload"`
}

func (m *ExecResponse) Reset()         { *m = ExecResponse{} }
func (m *ExecResponse) String() string { return proto.CompactTextString(m) }
func (*ExecResponse) ProtoMessage()    {}
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_72adf7ebfea3b2f6, []int{3}
}
func (m *ExecResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExecResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExecResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ExecResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecResponse.Merge(m, src)
}
func (m *ExecResponse) XXX_Size() int {
	return m.Size()
}
func (m *ExecResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecResponse proto.InternalMessageInfo

type isExecResponse_Payload interface {
	isExecResponse_Payload()
	MarshalTo([]byte) (int, error)
	Size() int
}

type ExecResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof" json:"stdout,omitempty"`
}
type ExecResponse_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof" json:"stderr,omitempty"`
}
type ExecResponse_ExitCode struct {
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exitCode,omitempty"`
}
type ExecResponse_Error struct {
	Error string `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (*ExecResponse_Stdout) isExecResponse_Payload()   {}
func (*ExecResponse_Stderr) isExecResponse_Payload()   {}
func (*ExecResponse_ExitCode) isExecResponse_Payload() {}
func (*ExecResponse_Error) isExecResponse_Payload()    {}

func (m *ExecResponse) GetPayload() isExecResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ExecResponse) GetStdout() []byte {
	if x, ok := m.GetPayload().(*ExecResponse_Stdout); ok {
		return x.Stdout
	}
	return nil
}

func (m *ExecResponse) GetStderr() []byte {
	if x, ok := m.GetPayload().(*ExecResponse_Stderr); ok {
		return x.Stderr
	}
	return nil
}

func (m *ExecResponse) GetExitCode() int32 {
	if x, ok := m.GetPayload().(*ExecResponse_ExitCode); ok {
		return x.ExitCode
	}
	return 0
}

func (m *ExecResponse) GetError() string {
	if x, ok := m.GetPayload().(*ExecResponse_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ExecResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ExecResponse_Stdout)(nil),
		(*ExecResponse_Stderr)(nil),
		(*ExecResponse_ExitCode)(nil),
		(*ExecResponse_Error)(nil),
	}
}

func init() {
	proto.RegisterType((*ExecRequest)(nil), "api.ExecRequest")
	proto.RegisterType((*ExecInit)(nil), "api.ExecInit")
	proto.RegisterType((*ExecResize)(nil), "api.ExecResize")
	proto.RegisterType((*ExecResponse)(nil), "api.ExecResponse")
}

func init() { proto.RegisterFile("pkg/api/interactive.proto", fileDescriptor_72adf7ebfea3b2f6) }

var fileDescriptor_72adf7ebfea3b2f6 = []byte{
	// 565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0x41, 0x8f, 0xd2, 0x4e,
	0x18, 0xc6, 0xe9, 0x02, 0x05, 0x66, 0xe1, 0xbf, 0xcb, 0xec, 0x5f, 0xad, 0x1e, 0x5a, 0x82, 0x07,
	0x51, 0x37, 0xd4, 0xac, 0x51, 0x8f, 0xc6, 0x9a, 0x4d, 0xe4, 0xe2, 0x01, 0x6f, 0x5e, 0x48, 0xe9,
	0xbc, 0x81, 0x41, 0xdb, 0xa9, 0xc3, 0x74, 0x5d, 0xfc, 0x14, 0x7e, 0x23, 0xaf, 0x1e, 0x37, 0x9e,
	0xbc, 0xd8, 0x18, 0xb8, 0xf5, 0x53, 0x98, 0xbe, 0x6d, 0xa1, 0x8d, 0x1e, 0xf9, 0xcd, 0xf3, 0x30,
	0xd3, 0xf7, 0x79, 0x5e, 0x72, 0x37, 0xfc, 0xb0, 0xb0, 0xdd, 0x90, 0xdb, 0x3c, 0x50, 0x20, 0x5d,
	0x4f, 0xf1, 0x2b, 0x18, 0x87, 0x52, 0x28, 0x41, 0xeb, 0x6e, 0xc8, 0x87, 0xdf, 0x34, 0x72, 0x7c,
	0x79, 0x0d, 0xde, 0x14, 0x3e, 0x45, 0xb0, 0x56, 0xf4, 0x05, 0x69, 0xf0, 0x80, 0x2b, 0x43, 0x1b,
	0x68, 0xa3, 0xe3, 0x8b, 0xde, 0xd8, 0x0d, 0xf9, 0x38, 0x3d, 0x9f, 0x04, 0x5c, 0x39, 0x34, 0x89,
	0xad, 0xff, 0xd2, 0xe3, 0x73, 0xe1, 0x73, 0x05, 0x7e, 0xa8, 0x36, 0x6f, 0x6a, 0x53, 0x34, 0xd0,
	0xc7, 0xa4, 0xb9, 0x56, 0x8c, 0x07, 0xc6, 0xd1, 0x40, 0x1b, 0x75, 0x9d, 0xb3, 0x24, 0xb6, 0x4e,
	0x10, 0x54, 0xb4, 0x99, 0x86, 0xbe, 0x24, 0xba, 0x84, 0x35, 0xff, 0x02, 0x46, 0x1d, 0xef, 0x39,
	0xd9, 0xdf, 0x33, 0x45, 0xec, 0xfc, 0x9f, 0xc4, 0xd6, 0x69, 0x26, 0xa9, 0xf8, 0x73, 0x9b, 0xd3,
	0x21, 0xad, 0xd0, 0xdd, 0x7c, 0x14, 0x2e, 0x1b, 0xfe, 0x38, 0x22, 0xed, 0xe2, 0x85, 0xf4, 0x11,
	0xd1, 0x57, 0x62, 0x3e, 0xe3, 0x0c, 0x3f, 0xa0, 0x93, 0x3d, 0x63, 0x25, 0xe6, 0x13, 0x76, 0xf8,
	0x9b, 0x69, 0x13, 0x41, 0xaa, 0x95, 0x51, 0x90, 0x6a, 0x8f, 0x0e, 0x5a, 0x19, 0x05, 0x55, 0x2d,
	0x02, 0xfa, 0x9c, 0x90, 0x50, 0xb0, 0x59, 0x10, 0xf9, 0x73, 0x90, 0xf8, 0xe8, 0xa6, 0x73, 0x27,
	0x89, 0xad, 0xb3, 0x50, 0xb0, 0xb7, 0x08, 0x4b, 0x9e, 0xce, 0x1e, 0xd2, 0x67, 0xa4, 0xe3, 0x89,
	0x40, 0xb9, 0x3c, 0x00, 0x69, 0x34, 0xf0, 0x1a, 0xb4, 0xed, 0x61, 0xd9, 0xb6, 0x87, 0xd4, 0x26,
	0x2d, 0x4f, 0xf8, 0xbe, 0x1b, 0x30, 0xa3, 0x39, 0xa8, 0x8f, 0x3a, 0xce, 0xad, 0x24, 0xb6, 0xfa,
	0x39, 0x2a, 0x59, 0x0a, 0x15, 0xbd, 0x4f, 0xea, 0x4a, 0x6d, 0x0c, 0x7d, 0xa0, 0x8d, 0xda, 0x4e,
	0x3f, 0x89, 0xad, 0x9e, 0x52, 0x9b, 0x92, 0x30, 0x3d, 0xa5, 0x0f, 0x8b, 0x88, 0x5a, 0x28, 0xfb,
	0x57, 0x44, 0x79, 0x40, 0x43, 0x20, 0xe4, 0x90, 0x46, 0x6a, 0xfc, 0xcc, 0x99, 0x5a, 0xe2, 0x50,
	0x7b, 0x99, 0x11, 0x41, 0xd9, 0x88, 0x80, 0x9e, 0x13, 0x7d, 0x09, 0x7c, 0xb1, 0x54, 0x38, 0xd4,
	0x5e, 0x16, 0x64, 0x46, 0x4a, 0xe2, 0x5c, 0x33, 0xfc, 0xa5, 0x91, 0x6e, 0x7e, 0x4f, 0x28, 0x82,
	0x35, 0xd0, 0x31, 0xd1, 0xd7, 0x8a, 0x89, 0x28, 0x2b, 0x60, 0x37, 0xb3, 0x67, 0xa4, 0xda, 0x83,
	0x8c, 0xe5, 0x7a, 0x90, 0x32, 0xaf, 0x5d, 0xa1, 0x07, 0x29, 0xff, 0xd2, 0x83, 0xc4, 0x3c, 0xe0,
	0x9a, 0xab, 0x99, 0x27, 0x18, 0xe4, 0x31, 0xde, 0x4e, 0x62, 0x8b, 0xa6, 0xf0, 0xb5, 0x60, 0xd5,
	0xb2, 0xb5, 0x0b, 0x9a, 0x96, 0x1b, 0xa4, 0x14, 0x45, 0x84, 0x38, 0x00, 0x04, 0xd5, 0x72, 0x23,
	0x2a, 0x75, 0xf3, 0xe2, 0x92, 0xd0, 0xc9, 0x61, 0xef, 0xde, 0x81, 0xbc, 0xe2, 0x1e, 0x50, 0x9b,
	0x34, 0xd2, 0x8f, 0xa6, 0xa7, 0xa5, 0xd6, 0xe3, 0xf6, 0xdd, 0xeb, 0x97, 0xf7, 0x00, 0x27, 0x32,
	0xd2, 0x9e, 0x68, 0xce, 0xab, 0xef, 0x5b, 0x53, 0xbb, 0xd9, 0x9a, 0xda, 0xef, 0xad, 0xa9, 0x7d,
	0xdd, 0x99, 0xb5, 0x9b, 0x9d, 0x59, 0xfb, 0xb9, 0x33, 0x6b, 0xef, 0x1f, 0x2c, 0xb8, 0x5a, 0x46,
	0xf3, 0xb1, 0x27, 0x7c, 0xdb, 0x95, 0xbe, 0xcb, 0xdc, 0x50, 0x8a, 0x15, 0x78, 0x2a, 0xff, 0x65,
	0xe7, 0xeb, 0x3f, 0xd7, 0x71, 0xe7, 0x9f, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x13, 0x1e, 0x27,
	0xd7, 0x10, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InteractiveServiceClient is the client API for InteractiveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InteractiveServiceClient interface {
	// Exec opens an interactive exec session to a running job's pod.
	// The first message from the client must be an ExecInit; subsequent messages
	// carry stdin data and terminal resize events.
	Exec(ctx context.Context, opts ...grpc.CallOption) (InteractiveService_ExecClient, error)
}

type interactiveServiceClient struct {
	cc *grpc.ClientConn
}

func NewInteractiveServiceClient(cc *grpc.ClientConn) InteractiveServiceClient {
	return &interactiveServiceClient{cc}
}

func (c *interactiveServiceClient) Exec(ctx context.Context, opts ...grpc.CallOption) (InteractiveService_ExecClient, error) {
	stream, err := c.cc.NewStream(ctx, &_InteractiveService_serviceDesc.Streams[0], "/api.InteractiveService/Exec", opts...)
	if err != nil {
		return nil, err
	}
	x := &interactiveServiceExecClient{stream}
	return x, nil
}

type InteractiveService_ExecClient interface {
	Send(*ExecRequest) error
	Recv() (*ExecResponse, error)
	grpc.ClientStream
}

type interactiveServiceExecClient struct {
	grpc.ClientStream
}

func (x *interactiveServiceExecClient) Send(m *ExecRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *interactiveServiceExecClient) Recv() (*ExecResponse, error) {
	m := new(ExecResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// InteractiveServiceServer is the server API for InteractiveService service.
type InteractiveServiceServer interface {
	// Exec opens an interactive exec session to a running job's pod.
	// The first message from the client must be an ExecInit; subsequent messages
	// carry stdin data and terminal resize events.
	Exec(InteractiveService_ExecServer) error
}

// UnimplementedInteractiveServiceServer can be embedded to have forward compatible implementations.
type UnimplementedInteractiveServiceServer struct {
}

func (*UnimplementedInteractiveServiceServer) Exec(srv InteractiveService_ExecServer) error {
	return status.Errorf(codes.Unimplemented, "method Exec not implemented")
}

func RegisterInteractiveServiceServer(s *grpc.Server, srv InteractiveServiceServer) {
	s.RegisterService(&_InteractiveService_serviceDesc, srv)
}

func _InteractiveService_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InteractiveServiceServer).Exec(&interactiveServiceExecServer{stream})
}

type InteractiveService_ExecServer interface {
	Send(*ExecResponse) error
	Recv() (*ExecRequest, error)
	grpc.ServerStream
}

type interactiveServiceExecServer struct {
	grpc.ServerStream
}

func (x *interactiveServiceExecServer) Send(m *ExecResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *interactiveServiceExecServer) Recv() (*ExecRequest, error) {
	m := new(ExecRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _InteractiveService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.InteractiveService",
	HandlerType: (*InteractiveServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _InteractiveService_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/api/interactive.proto",
}

func (m *ExecRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExecRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExecRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Payload != nil {
		{
			size := m.Payload.Size()
			i -= size
			if _, err := m.Payload.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *ExecRequest_Init) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExecRequest_Init) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Init != nil {
		{
			size, err := m.Init.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintInteractive(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *ExecRequest_Stdin) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExecRequest_Stdin) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Stdin != nil {
		i -= len(m.Stdin)
		copy(dAtA[i:], m.Stdin)
		i = encodeVarintInteractive(dAtA, i, uint64(len(m.Stdin)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *ExecRequest_Resize) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExecRequest_Resize) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Resize != nil {
		{
			size, err := m.Resize.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintInteractive(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *ExecInit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExecInit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExecInit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Stdin {
		i--
		if m.Stdin {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.Tty {
		i--
		if m.Tty {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if len(m.Command) > 0 {
		for iNdEx := len(m.Command) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Command[iNdEx])
			copy(dAtA[i:], m.Command[iNdEx])
			i = encodeVarintInteractive(dAtA, i, uint64(len(m.Command[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Container) > 0 {
		i -= len(m.Container)
		copy(dAtA[i:], m.Container)
		i = encodeVarintInteractive(dAtA, i, uint64(len(m.Container)))
		i--
		dAtA[i] = 0x22
	}
	if m.PodNumber != 0 {
		i = encodeVarintInteractive(dAtA, i, uint64(m.PodNumber))
		i--
		dAtA[i] = 0x18
	}
	if len(m.RunId) > 0 {
		i -= len(m.RunId)
		copy(dAtA[i:], m.RunId)
		i = encodeVarintInteractive(dAtA, i, uint64(len(m.RunId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.JobId) > 0 {
		i -= len(m.JobId)
		copy(dAtA[i:], m.JobId)
		i = encodeVarintInteractive(dAtA, i, uint64(len(m.JobId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ExecResize) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExecResize) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExecResize) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintInteractive(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x10
	}
	if m.Width != 0 {
		i = encodeVarintInteractive(dAtA, i, uint64(m.Width))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ExecResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExecResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExecResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Payload != nil {
		{
			size := m.Payload.Size()
			i -= size
			if _, err := m.Payload.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *ExecResponse_Stdout) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExecResponse_Stdout) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Stdout != nil {
		i -= len(m.Stdout)
		copy(dAtA[i:], m.Stdout)
		i = encodeVarintInteractive(dAtA, i, uint64(len(m.Stdout)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *ExecResponse_Stderr) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExecResponse_Stderr) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Stderr != nil {
		i -= len(m.Stderr)
		copy(dAtA[i:], m.Stderr)
		i = encodeVarintInteractive(dAtA, i, uint64(len(m.Stderr)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *ExecResponse_ExitCode) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExecResponse_ExitCode) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintInteractive(dAtA, i, uint64(m.ExitCode))
	i--
	dAtA[i] = 0x18
	return len(dAtA) - i, nil
}
func (m *ExecResponse_Error) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExecResponse_Error) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= len(m.Error)
	copy(dAtA[i:], m.Error)
	i = encodeVarintInteractive(dAtA, i, uint64(len(m.Error)))
	i--
	dAtA[i] = 0x22
	return len(dAtA) - i, nil
}
func encodeVarintInteractive(dAtA []byte, offset int, v uint64) int {
	offset -= sovInteractive(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ExecRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Payload != nil {
		n += m.Payload.Size()
	}
	return n
}

func (m *ExecRequest_Init) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Init != nil {
		l = m.Init.Size()
		n += 1 + l + sovInteractive(uint64(l))
	}
	return n
}
func (m *ExecRequest_Stdin) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Stdin != nil {
		l = len(m.Stdin)
		n += 1 + l + sovInteractive(uint64(l))
	}
	return n
}
func (m *ExecRequest_Resize) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Resize != nil {
		l = m.Resize.Size()
		n += 1 + l + sovInteractive(uint64(l))
	}
	return n
}
func (m *ExecInit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.JobId)
	if l > 0 {
		n += 1 + l + sovInteractive(uint64(l))
	}
	l = len(m.RunId)
	if l > 0 {
		n += 1 + l + sovInteractive(uint64(l))
	}
	if m.PodNumber != 0 {
		n += 1 + sovInteractive(uint64(m.PodNumber))
	}
	l = len(m.Container)
	if l > 0 {
		n += 1 + l + sovInteractive(uint64(l))
	}
	if len(m.Command) > 0 {
		for _, s := range m.Command {
			l = len(s)
			n += 1 + l + sovInteractive(uint64(l))
		}
	}
	if m.Tty {
		n += 2
	}
	if m.Stdin {
		n += 2
	}
	return n
}

func (m *ExecResize) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Width != 0 {
		n += 1 + sovInteractive(uint64(m.Width))
	}
	if m.Height != 0 {
		n += 1 + sovInteractive(uint64(m.Height))
	}
	return n
}

func (m *ExecResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Payload != nil {
		n += m.Payload.Size()
	}
	return n
}

func (m *ExecResponse_Stdout) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Stdout != nil {
		l = len(m.Stdout)
		n += 1 + l + sovInteractive(uint64(l))
	}
	return n
}
func (m *ExecResponse_Stderr) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Stderr != nil {
		l = len(m.Stderr)
		n += 1 + l + sovInteractive(uint64(l))
	}
	return n
}
func (m *ExecResponse_ExitCode) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovInteractive(uint64(m.ExitCode))
	return n
}
func (m *ExecResponse_Error) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Error)
	n += 1 + l + sovInteractive(uint64(l))
	return n
}

func sovInteractive(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozInteractive(x uint64) (n int) {
	return sovInteractive(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ExecRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInteractive
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExecRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExecRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Init", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInteractive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInteractive
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInteractive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ExecInit{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Payload = &ExecRequest_Init{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stdin", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInteractive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthInteractive
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthInteractive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := make([]byte, postIndex-iNdEx)
			copy(v, dAtA[iNdEx:postIndex])
			m.Payload = &ExecRequest_Stdin{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Resize", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInteractive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInteractive
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInteractive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ExecResize{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Payload = &ExecRequest_Resize{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInteractive(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInteractive
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExecInit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInteractive
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExecInit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExecInit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInteractive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInteractive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInteractive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JobId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RunId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInteractive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInteractive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInteractive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RunId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PodNumber", wireType)
			}
			m.PodNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInteractive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PodNumber |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Container", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInteractive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInteractive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInteractive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Container = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Command", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInteractive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInteractive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInteractive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Command = append(m.Command, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tty", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInteractive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Tty = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stdin", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInteractive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Stdin = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipInteractive(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInteractive
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExecResize) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInteractive
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExecResize: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExecResize: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Width", wireType)
			}
			m.Width = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInteractive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Width |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInteractive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipInteractive(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInteractive
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExecResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInteractive
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExecResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExecResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stdout", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInteractive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthInteractive
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthInteractive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := make([]byte, postIndex-iNdEx)
			copy(v, dAtA[iNdEx:postIndex])
			m.Payload = &ExecResponse_Stdout{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stderr", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInteractive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthInteractive
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthInteractive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := make([]byte, postIndex-iNdEx)
			copy(v, dAtA[iNdEx:postIndex])
			m.Payload = &ExecResponse_Stderr{v}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExitCode", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInteractive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Payload = &ExecResponse_ExitCode{v}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInteractive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInteractive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInteractive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = &ExecResponse_Error{string(dAtA[iNdEx:postIndex])}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInteractive(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInteractive
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipInteractive(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowInteractive
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInteractive
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInteractive
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthInteractive
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupInteractive
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthInteractive
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthInteractive        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowInteractive          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupInteractive = fmt.Errorf("proto: unexpected end of group")
)
