application:
  errorCategories:
    enabled: true
    defaultCategory: "uncategorized"
    categories:
      - name: oom
        rules:
          - onConditions: ["OOMKilled"]
      - name: user_error
        rules:
          - onExitCodes:
              operator: In
              values: [1, 2, 126, 127]
