global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "armada-lookout"
    static_configs:
      - targets: ["host.docker.internal:9003"]

  - job_name: "armada-scheduler"
    static_configs:
      - targets: ["host.docker.internal:9004"]

  - job_name: "armada-server"
    static_configs:
      - targets: ["host.docker.internal:9005"]

  - job_name: "armada-lookout-ingester"
    static_configs:
      - targets: ["host.docker.internal:9006"]

  - job_name: "armada-event-ingester"
    static_configs:
      - targets: ["host.docker.internal:9011"]

  - job_name: "armada-binoculars"
    static_configs:
      - targets: ["host.docker.internal:9012"]
