submissions:
  - name: example
    queue: regatta-example
    count: 5
    jobs:
      - name: basic_job
        count: 10
        namespace: default
        spec:
          terminationGracePeriodSeconds: 0
          restartPolicy: Never
          nodeSelector:
            kwok.x-k8s.io/node: fake
          tolerations:
            - key: kwok.x-k8s.io/node
              operator: Equal
              value: fake
              effect: NoSchedule
          containers:
            - name: sleep
              imagePullPolicy: IfNotPresent
              image: alpine:3.21.3
              command:
                - sh
              args:
                - -c
                - sleep $(( (RANDOM % 60) + 100 ))
              resources:
                limits:
                  memory: 64Mi
                  cpu: 60m
                requests:
                  memory: 64Mi
                  cpu: 60m
