// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/metricevents/events.proto

package metricevents

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Created *types.Timestamp `protobuf:"bytes,1,opt,name=created,proto3" json:"created,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*Event_CycleMetrics
	Event isEvent_Event `protobuf_oneof:"event"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_932dcac363ef0bc9, []int{0}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Event.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return m.Size()
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

type isEvent_Event interface {
	isEvent_Event()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Event_CycleMetrics struct {
	CycleMetrics *CycleMetrics `protobuf:"bytes,2,opt,name=cycle_metrics,json=cycleMetrics,proto3,oneof" json:"cycleMetrics,omitempty"`
}

func (*Event_CycleMetrics) isEvent_Event() {}

func (m *Event) GetEvent() isEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Event) GetCreated() *types.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Event) GetCycleMetrics() *CycleMetrics {
	if x, ok := m.GetEvent().(*Event_CycleMetrics); ok {
		return x.CycleMetrics
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Event) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Event_CycleMetrics)(nil),
	}
}

type QueueMetrics struct {
	// Fraction of the pool allocated
	ActualShare float64 `protobuf:"fixed64,1,opt,name=actual_share,json=actualShare,proto3" json:"actualShare,omitempty"`
	// Fraction of the pool demanded. May be greater than 1
	Demand float64 `protobuf:"fixed64,2,opt,name=demand,proto3" json:"demand,omitempty"`
	// Fraction of the pool demanded, limited by scheduling constraints. May be greater than 1
	ConstrainedDemand float64 `protobuf:"fixed64,3,opt,name=constrained_demand,json=constrainedDemand,proto3" json:"constrainedDemand,omitempty"`
	// Demand per resource
	DemandByResourceType map[string]*resource.Quantity `protobuf:"bytes,4,rep,name=demand_by_resource_type,json=demandByResourceType,proto3" json:"demandByResourceType,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Constrained Demand per resource
	ConstrainedDemandByResourceType map[string]*resource.Quantity `protobuf:"bytes,5,rep,name=constrained_demand_by_resource_type,json=constrainedDemandByResourceType,proto3" json:"constrainedDemandByResourceType,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Short job penalty as a fraction of the pool
	ShortJobPenalty float64 `protobuf:"fixed64,6,opt,name=short_job_penalty,json=shortJobPenalty,proto3" json:"shortJobPenalty,omitempty"`
}

func (m *QueueMetrics) Reset()         { *m = QueueMetrics{} }
func (m *QueueMetrics) String() string { return proto.CompactTextString(m) }
func (*QueueMetrics) ProtoMessage()    {}
func (*QueueMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_932dcac363ef0bc9, []int{1}
}
func (m *QueueMetrics) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueueMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueueMetrics.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueueMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueMetrics.Merge(m, src)
}
func (m *QueueMetrics) XXX_Size() int {
	return m.Size()
}
func (m *QueueMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_QueueMetrics proto.InternalMessageInfo

func (m *QueueMetrics) GetActualShare() float64 {
	if m != nil {
		return m.ActualShare
	}
	return 0
}

func (m *QueueMetrics) GetDemand() float64 {
	if m != nil {
		return m.Demand
	}
	return 0
}

func (m *QueueMetrics) GetConstrainedDemand() float64 {
	if m != nil {
		return m.ConstrainedDemand
	}
	return 0
}

func (m *QueueMetrics) GetDemandByResourceType() map[string]*resource.Quantity {
	if m != nil {
		return m.DemandByResourceType
	}
	return nil
}

func (m *QueueMetrics) GetConstrainedDemandByResourceType() map[string]*resource.Quantity {
	if m != nil {
		return m.ConstrainedDemandByResourceType
	}
	return nil
}

func (m *QueueMetrics) GetShortJobPenalty() float64 {
	if m != nil {
		return m.ShortJobPenalty
	}
	return 0
}

type CycleMetrics struct {
	// Pool that these metrics pertain to
	Pool string `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	// Per-Queue Metrics
	QueueMetrics map[string]*QueueMetrics `protobuf:"bytes,2,rep,name=queue_metrics,json=queueMetrics,proto3" json:"queueMetrics,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Allocatable resources
	AllocatableResources map[string]*resource.Quantity `protobuf:"bytes,3,rep,name=allocatable_resources,json=allocatableResources,proto3" json:"allocatableResources,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *CycleMetrics) Reset()         { *m = CycleMetrics{} }
func (m *CycleMetrics) String() string { return proto.CompactTextString(m) }
func (*CycleMetrics) ProtoMessage()    {}
func (*CycleMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_932dcac363ef0bc9, []int{2}
}
func (m *CycleMetrics) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CycleMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CycleMetrics.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CycleMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CycleMetrics.Merge(m, src)
}
func (m *CycleMetrics) XXX_Size() int {
	return m.Size()
}
func (m *CycleMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_CycleMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_CycleMetrics proto.InternalMessageInfo

func (m *CycleMetrics) GetPool() string {
	if m != nil {
		return m.Pool
	}
	return ""
}

func (m *CycleMetrics) GetQueueMetrics() map[string]*QueueMetrics {
	if m != nil {
		return m.QueueMetrics
	}
	return nil
}

func (m *CycleMetrics) GetAllocatableResources() map[string]*resource.Quantity {
	if m != nil {
		return m.AllocatableResources
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "metricevents.Event")
	proto.RegisterType((*QueueMetrics)(nil), "metricevents.QueueMetrics")
	proto.RegisterMapType((map[string]*resource.Quantity)(nil), "metricevents.QueueMetrics.ConstrainedDemandByResourceTypeEntry")
	proto.RegisterMapType((map[string]*resource.Quantity)(nil), "metricevents.QueueMetrics.DemandByResourceTypeEntry")
	proto.RegisterType((*CycleMetrics)(nil), "metricevents.CycleMetrics")
	proto.RegisterMapType((map[string]*resource.Quantity)(nil), "metricevents.CycleMetrics.AllocatableResourcesEntry")
	proto.RegisterMapType((map[string]*QueueMetrics)(nil), "metricevents.CycleMetrics.QueueMetricsEntry")
}

func init() { proto.RegisterFile("pkg/metricevents/events.proto", fileDescriptor_932dcac363ef0bc9) }

var fileDescriptor_932dcac363ef0bc9 = []byte{
	// 730 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xcf, 0x4f, 0xd4, 0x4e,
	0x14, 0xdf, 0x61, 0x59, 0xc8, 0x77, 0x58, 0xbe, 0x7c, 0x77, 0xbe, 0xa0, 0x4b, 0x0d, 0x5b, 0xb2,
	0x18, 0x83, 0x09, 0x4e, 0x0d, 0x72, 0x20, 0xc6, 0xc4, 0x58, 0x24, 0x51, 0x8c, 0x46, 0x90, 0x8b,
	0x26, 0xa6, 0x99, 0xed, 0x8e, 0xbb, 0x65, 0xdb, 0x4e, 0x69, 0xa7, 0x24, 0x3d, 0x7b, 0x36, 0xfa,
	0x1f, 0x78, 0xf7, 0xee, 0x8d, 0x3f, 0xc0, 0x23, 0x47, 0x2f, 0x36, 0x06, 0x6e, 0xfd, 0x2b, 0x4c,
	0x3b, 0xad, 0xcc, 0xfe, 0x02, 0x8e, 0x9c, 0x9a, 0xbe, 0xcf, 0x7b, 0x9f, 0xf7, 0x79, 0xf3, 0xde,
	0x9b, 0x81, 0x4b, 0x5e, 0xaf, 0xa3, 0x39, 0x94, 0xfb, 0x96, 0x49, 0x8f, 0xa8, 0xcb, 0x03, 0x4d,
	0x7c, 0xb0, 0xe7, 0x33, 0xce, 0x50, 0x55, 0x86, 0x14, 0xb5, 0xc3, 0x58, 0xc7, 0xa6, 0x5a, 0x86,
	0xb5, 0xc2, 0x0f, 0x1a, 0xb7, 0x1c, 0x1a, 0x70, 0xe2, 0x78, 0xc2, 0x5d, 0xd9, 0xe8, 0x6d, 0x06,
	0xd8, 0x62, 0x1a, 0xf1, 0x2c, 0x87, 0x98, 0x5d, 0xcb, 0xa5, 0x7e, 0xa4, 0xa5, 0x19, 0x88, 0x67,
	0x69, 0x3e, 0x0d, 0x58, 0xe8, 0x9b, 0x54, 0xeb, 0x50, 0x97, 0xfa, 0x84, 0xd3, 0xb6, 0x88, 0x6a,
	0x1e, 0x03, 0x58, 0xd9, 0x4e, 0x33, 0xa0, 0x17, 0x70, 0xda, 0xf4, 0x69, 0x0a, 0xd5, 0xc1, 0x32,
	0x58, 0x9d, 0x59, 0x57, 0xb0, 0x48, 0x89, 0x8b, 0x94, 0x78, 0xbf, 0x48, 0xa9, 0x2f, 0x24, 0xb1,
	0x5a, 0xcb, 0xdd, 0xd7, 0x98, 0x63, 0x71, 0xea, 0x78, 0x3c, 0xda, 0x2b, 0x18, 0xd0, 0x7b, 0x38,
	0x6b, 0x46, 0xa6, 0x4d, 0x0d, 0x51, 0x43, 0x50, 0x9f, 0xc8, 0x29, 0xe5, 0x9a, 0xf0, 0x56, 0xea,
	0xf2, 0x52, 0x78, 0xe8, 0x4a, 0x12, 0xab, 0x37, 0x4c, 0xc9, 0x72, 0xce, 0xfb, 0xac, 0xb4, 0x57,
	0x95, 0x11, 0x7d, 0x1a, 0x56, 0x32, 0x8a, 0xe6, 0xf7, 0x69, 0x58, 0xdd, 0x0d, 0x69, 0x58, 0x20,
	0xe8, 0x11, 0xac, 0x12, 0x93, 0x87, 0xc4, 0x36, 0x82, 0x2e, 0xf1, 0x69, 0x56, 0x0a, 0xd0, 0x17,
	0x93, 0x58, 0x5d, 0x10, 0xf6, 0x37, 0xa9, 0x59, 0x92, 0x3c, 0x23, 0x99, 0xd1, 0x1a, 0x9c, 0x6a,
	0x53, 0x87, 0xb8, 0xed, 0x4c, 0x2f, 0xd0, 0xe7, 0x93, 0x58, 0xfd, 0x4f, 0x58, 0xa4, 0x90, 0xdc,
	0x07, 0xbd, 0x82, 0xc8, 0x64, 0x6e, 0xc0, 0x7d, 0x62, 0xb9, 0xb4, 0x6d, 0xe4, 0x91, 0xe5, 0x2c,
	0x52, 0x4d, 0x62, 0xf5, 0x96, 0x84, 0x3e, 0x1d, 0x24, 0xa9, 0x0d, 0x81, 0xe8, 0x33, 0x80, 0x37,
	0x05, 0x89, 0xd1, 0x8a, 0x8c, 0xa2, 0x65, 0x06, 0x8f, 0x3c, 0x5a, 0x9f, 0x5c, 0x2e, 0xaf, 0xce,
	0xac, 0x6f, 0xf4, 0x9f, 0x9f, 0x5c, 0x39, 0x16, 0x24, 0x7a, 0xb4, 0x97, 0xc7, 0xed, 0x47, 0x1e,
	0xdd, 0x76, 0xb9, 0x1f, 0xe9, 0xcd, 0x24, 0x56, 0x1b, 0xed, 0x11, 0xb0, 0x24, 0x67, 0x7e, 0x14,
	0x8e, 0x8e, 0x01, 0x5c, 0x19, 0x2e, 0x71, 0x58, 0x5d, 0x25, 0x53, 0xf7, 0xf8, 0x02, 0x75, 0x5b,
	0x83, 0xd5, 0x8e, 0x12, 0x7a, 0x2f, 0x89, 0xd5, 0xbb, 0xe6, 0xc5, 0x9e, 0x92, 0x66, 0xf5, 0x12,
	0x57, 0xf4, 0x1c, 0xd6, 0x82, 0x2e, 0xf3, 0xb9, 0x71, 0xc0, 0x5a, 0x86, 0x47, 0x5d, 0x62, 0xf3,
	0xa8, 0x3e, 0x95, 0xf5, 0x67, 0x29, 0x89, 0xd5, 0xc5, 0x0c, 0xdc, 0x61, 0xad, 0xd7, 0x02, 0x92,
	0xa8, 0xe7, 0x06, 0x20, 0xe5, 0x2b, 0x80, 0x8b, 0x63, 0x85, 0xa3, 0x15, 0x58, 0xee, 0xd1, 0x28,
	0x1b, 0xb6, 0x7f, 0xf4, 0x5a, 0x12, 0xab, 0xb3, 0x3d, 0x2a, 0xd3, 0xa5, 0x28, 0x7a, 0x0b, 0x2b,
	0x47, 0xc4, 0x0e, 0x69, 0xbe, 0x0b, 0x18, 0x8b, 0x85, 0xc5, 0xf2, 0xc2, 0x62, 0xaf, 0xd7, 0x49,
	0x0d, 0xb8, 0x38, 0x5f, 0xbc, 0x1b, 0x12, 0x97, 0x5b, 0x3c, 0xd2, 0xff, 0x4f, 0x62, 0x75, 0x2e,
	0x23, 0x90, 0x88, 0x05, 0xe3, 0xc3, 0x89, 0x4d, 0xa0, 0x7c, 0x03, 0xf0, 0xf6, 0x55, 0x4e, 0xf9,
	0x3a, 0x88, 0x6d, 0xfe, 0x9a, 0x84, 0x55, 0x79, 0xfb, 0xd1, 0x1d, 0x38, 0xe9, 0x31, 0x66, 0xe7,
	0xaa, 0x50, 0x12, 0xab, 0xff, 0xa6, 0xff, 0x52, 0x74, 0x86, 0x23, 0x07, 0xce, 0x1e, 0xa6, 0x73,
	0x25, 0x5d, 0x2c, 0xe9, 0xe8, 0xad, 0x8d, 0xbf, 0x58, 0xfa, 0xe6, 0x50, 0xcc, 0x59, 0x76, 0xd5,
	0x1c, 0x4a, 0x66, 0x29, 0x4d, 0x55, 0xb6, 0xa3, 0x4f, 0x00, 0x2e, 0x10, 0xdb, 0x66, 0x26, 0xe1,
	0xa4, 0x65, 0xd3, 0xbf, 0x63, 0x1f, 0xd4, 0xcb, 0xa3, 0x16, 0xb2, 0x2f, 0xef, 0x93, 0xf3, 0xb8,
	0xa2, 0x09, 0x81, 0xb4, 0x90, 0x64, 0x04, 0x2c, 0x2f, 0xe4, 0x28, 0x5c, 0xf9, 0x08, 0x60, 0x6d,
	0xa8, 0x9e, 0xab, 0x75, 0x74, 0xbb, 0xbf, 0xa3, 0xca, 0xf8, 0x65, 0xbd, 0x74, 0xd4, 0xd2, 0x65,
	0x18, 0x5b, 0xdd, 0x75, 0x98, 0x2f, 0x7d, 0xe7, 0xc7, 0x69, 0x03, 0x9c, 0x9c, 0x36, 0xc0, 0xef,
	0xd3, 0x06, 0xf8, 0x72, 0xd6, 0x28, 0x9d, 0x9c, 0x35, 0x4a, 0x3f, 0xcf, 0x1a, 0xa5, 0x77, 0xf7,
	0x3b, 0x16, 0xef, 0x86, 0x2d, 0x6c, 0x32, 0x47, 0x23, 0xbe, 0x43, 0xda, 0xc4, 0xf3, 0xd9, 0x01,
	0x35, 0x79, 0xfe, 0xa7, 0x0d, 0x3e, 0xca, 0xad, 0xa9, 0xec, 0xfd, 0x7b, 0xf0, 0x27, 0x00, 0x00,
	0xff, 0xff, 0xd0, 0xed, 0x81, 0xdb, 0xaf, 0x07, 0x00, 0x00,
}

func (m *Event) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Event) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Event) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Event != nil {
		{
			size := m.Event.Size()
			i -= size
			if _, err := m.Event.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.Created != nil {
		{
			size, err := m.Created.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvents(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Event_CycleMetrics) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Event_CycleMetrics) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.CycleMetrics != nil {
		{
			size, err := m.CycleMetrics.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvents(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *QueueMetrics) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueueMetrics) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueueMetrics) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ShortJobPenalty != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.ShortJobPenalty))))
		i--
		dAtA[i] = 0x31
	}
	if len(m.ConstrainedDemandByResourceType) > 0 {
		for k := range m.ConstrainedDemandByResourceType {
			v := m.ConstrainedDemandByResourceType[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintEvents(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintEvents(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintEvents(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.DemandByResourceType) > 0 {
		for k := range m.DemandByResourceType {
			v := m.DemandByResourceType[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintEvents(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintEvents(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintEvents(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.ConstrainedDemand != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.ConstrainedDemand))))
		i--
		dAtA[i] = 0x19
	}
	if m.Demand != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Demand))))
		i--
		dAtA[i] = 0x11
	}
	if m.ActualShare != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.ActualShare))))
		i--
		dAtA[i] = 0x9
	}
	return len(dAtA) - i, nil
}

func (m *CycleMetrics) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CycleMetrics) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CycleMetrics) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AllocatableResources) > 0 {
		for k := range m.AllocatableResources {
			v := m.AllocatableResources[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintEvents(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintEvents(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintEvents(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.QueueMetrics) > 0 {
		for k := range m.QueueMetrics {
			v := m.QueueMetrics[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintEvents(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintEvents(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintEvents(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Pool) > 0 {
		i -= len(m.Pool)
		copy(dAtA[i:], m.Pool)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Pool)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Event) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Created != nil {
		l = m.Created.Size()
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.Event != nil {
		n += m.Event.Size()
	}
	return n
}

func (m *Event_CycleMetrics) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CycleMetrics != nil {
		l = m.CycleMetrics.Size()
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}
func (m *QueueMetrics) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ActualShare != 0 {
		n += 9
	}
	if m.Demand != 0 {
		n += 9
	}
	if m.ConstrainedDemand != 0 {
		n += 9
	}
	if len(m.DemandByResourceType) > 0 {
		for k, v := range m.DemandByResourceType {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovEvents(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovEvents(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovEvents(uint64(mapEntrySize))
		}
	}
	if len(m.ConstrainedDemandByResourceType) > 0 {
		for k, v := range m.ConstrainedDemandByResourceType {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovEvents(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovEvents(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovEvents(uint64(mapEntrySize))
		}
	}
	if m.ShortJobPenalty != 0 {
		n += 9
	}
	return n
}

func (m *CycleMetrics) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Pool)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if len(m.QueueMetrics) > 0 {
		for k, v := range m.QueueMetrics {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovEvents(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovEvents(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovEvents(uint64(mapEntrySize))
		}
	}
	if len(m.AllocatableResources) > 0 {
		for k, v := range m.AllocatableResources {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovEvents(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovEvents(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovEvents(uint64(mapEntrySize))
		}
	}
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Event) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Event: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Event: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Created", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Created == nil {
				m.Created = &types.Timestamp{}
			}
			if err := m.Created.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CycleMetrics", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &CycleMetrics{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Event = &Event_CycleMetrics{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueueMetrics) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueueMetrics: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueueMetrics: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActualShare", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.ActualShare = float64(math.Float64frombits(v))
		case 2:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Demand", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Demand = float64(math.Float64frombits(v))
		case 3:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConstrainedDemand", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.ConstrainedDemand = float64(math.Float64frombits(v))
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DemandByResourceType", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DemandByResourceType == nil {
				m.DemandByResourceType = make(map[string]*resource.Quantity)
			}
			var mapkey string
			var mapvalue *resource.Quantity
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEvents
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEvents
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthEvents
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthEvents
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEvents
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthEvents
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthEvents
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &resource.Quantity{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipEvents(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthEvents
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.DemandByResourceType[mapkey] = mapvalue
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConstrainedDemandByResourceType", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConstrainedDemandByResourceType == nil {
				m.ConstrainedDemandByResourceType = make(map[string]*resource.Quantity)
			}
			var mapkey string
			var mapvalue *resource.Quantity
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEvents
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEvents
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthEvents
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthEvents
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEvents
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthEvents
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthEvents
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &resource.Quantity{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipEvents(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthEvents
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ConstrainedDemandByResourceType[mapkey] = mapvalue
			iNdEx = postIndex
		case 6:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShortJobPenalty", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.ShortJobPenalty = float64(math.Float64frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CycleMetrics) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CycleMetrics: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CycleMetrics: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pool", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pool = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueueMetrics", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.QueueMetrics == nil {
				m.QueueMetrics = make(map[string]*QueueMetrics)
			}
			var mapkey string
			var mapvalue *QueueMetrics
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEvents
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEvents
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthEvents
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthEvents
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEvents
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthEvents
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthEvents
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &QueueMetrics{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipEvents(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthEvents
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.QueueMetrics[mapkey] = mapvalue
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllocatableResources", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AllocatableResources == nil {
				m.AllocatableResources = make(map[string]*resource.Quantity)
			}
			var mapkey string
			var mapvalue *resource.Quantity
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEvents
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEvents
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthEvents
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthEvents
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEvents
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthEvents
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthEvents
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &resource.Quantity{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipEvents(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthEvents
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.AllocatableResources[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
