ALTER TABLE IF EXISTS jobs ALTER COLUMN queue SET STATISTICS 1000;
ALTER TABLE IF EXISTS jobs ALTER COLUMN job_set SET STATISTICS 1000;

CREATE STATISTICS IF NOT EXISTS stx_jobs_queue_job_set ON queue, job_set FROM jobs;
