postgres:
  connection:
    host: postgres
    port: 5433
    user: postgres
    password: psw
    dbname: lookout
    sslmode: disable
metricsPort: 9002
pulsar:
  URL: "pulsar://pulsar:6650"
  restURL: "http://localhost:8090"
  jobsetEventsTopic: "events"
  backoffTime: 1s
  maxBackoffTime: 30s
  backoffRandomizationFactor: 0.5
  backoffMultiplier: 1.5
  receiverQueueSize: 100
  deadLetterTopic: events-dead-letter
  deadLetterMaxAttempts: 5
  delayMonitor:
    enabled: false
    interval: 30s
subscriptionName: "lookout-ingester-v2"
batchSize: 10000
batchDuration: 500ms
minJobSpecCompressionSize: 1024
userAnnotationPrefix: "armadaproject.io/"
