global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "armada-server"
    static_configs:
      - targets: ["host.docker.internal:9009"]

  - job_name: "armada-scheduler"
    static_configs:
      - targets: ["host.docker.internal:9001"]

  - job_name: "armada-executor-1"
    static_configs:
      - targets: ["host.docker.internal:9002"]

  - job_name: "armada-executor-2"
    static_configs:
      - targets: ["host.docker.internal:9012"]

  - job_name: "armada-executor-3"
    static_configs:
      - targets: ["host.docker.internal:9022"]

  - job_name: "armada-executor-4"
    static_configs:
      - targets: ["host.docker.internal:9032"]

  - job_name: "armada-executor-5"
    static_configs:
      - targets: ["host.docker.internal:9042"]

  - job_name: "armada-executor-6"
    static_configs:
      - targets: ["host.docker.internal:9052"]

  - job_name: "armada-executor-7"
    static_configs:
      - targets: ["host.docker.internal:9062"]

  - job_name: "armada-executor-8"
    static_configs:
      - targets: ["host.docker.internal:9072"]

  - job_name: "armada-executor-9"
    static_configs:
      - targets: ["host.docker.internal:9082"]

  - job_name: "armada-executor-10"
    static_configs:
      - targets: ["host.docker.internal:9092"]

  - job_name: "armada-lookout"
    static_configs:
      - targets: ["host.docker.internal:9003"]

  - job_name: "armada-event-ingester"
    static_configs:
      - targets: ["host.docker.internal:9004"]

  - job_name: "armada-lookout-ingester"
    static_configs:
      - targets: ["host.docker.internal:9005"]

  - job_name: "armada-scheduler-ingester"
    static_configs:
      - targets: ["host.docker.internal:9006"]

  - job_name: "armada-binoculars"
    static_configs:
      - targets: ["host.docker.internal:9007"]
