redis:
  addrs:
    - localhost:6379
  db: 1
  poolSize: 1000
pulsar:
  URL: "pulsar://localhost:6650"
  restURL: "http://localhost:8090"
  jobsetEventsTopic: "events"
subscriptionName: "events-ingester"
metricsPort: 9004
metrics:
  redis:
    enabled: true
    collectionInterval: 30s
    topN: 100
    scanBatchSize: 1000
    pipelineBatchSize: 500
    interBatchDelay: 0ms
    memoryUsageSamples: 5
    connectionInfo:
      addrs:
        - localhost:6379
      db: 1
    leader:
      mode: "standalone"
      leaseLockName: ""
      leaseLockNamespace: ""
      leaseDuration: 15s
      renewDeadline: 10s
      retryPeriod: 2s
