server: ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-server ./cmd/server/main.go && ./dist/armada-server --config ./_local/server/config.yaml
scheduler: ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-scheduler ./cmd/scheduler/main.go && ./dist/armada-scheduler run --config ./_local/scheduler/config.yaml
scheduleringester: ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-scheduleringester ./cmd/scheduleringester/main.go && ./dist/armada-scheduleringester --config ./_local/scheduleringester/config.yaml
eventingester: ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-eventingester ./cmd/eventingester/main.go && ./dist/armada-eventingester --config ./_local/eventingester/config.yaml
executor-1: export KUBECONFIG=.kube/external/multicluster/cluster-1 && ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-executor-1 ./cmd/executor/main.go && ./dist/armada-executor-1 --config ./_local/executor/config.yaml,./_local/executor/two-cluster/config-cluster-1.yaml
executor-2: export KUBECONFIG=.kube/external/multicluster/cluster-2 && ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-executor-2 ./cmd/executor/main.go && ./dist/armada-executor-2 --config ./_local/executor/config.yaml,./_local/executor/two-cluster/config-cluster-2.yaml
lookout: ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-lookout ./cmd/lookout/main.go && ./dist/armada-lookout --config ./_local/lookout/config.yaml
lookoutingester: ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-lookoutingester ./cmd/lookoutingester/main.go && ./dist/armada-lookoutingester --config ./_local/lookoutingester/config.yaml
binoculars-1: export KUBECONFIG=.kube/external/multicluster/cluster-1 && ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-binoculars-1 ./cmd/binoculars/main.go && ./dist/armada-binoculars-1 --config ./_local/binoculars/config.yaml
binoculars-2: export KUBECONFIG=.kube/external/multicluster/cluster-2 && ${GO_BIN:-go} build -gcflags="all=-N -l" -o ./dist/armada-binoculars-2 ./cmd/binoculars/main.go && ./dist/armada-binoculars-2 --config ./_local/binoculars/config.yaml,./_local/binoculars/two-cluster/config-cluster-2.yaml
lookoutui: sh -c 'cd internal/lookoutui && yarn install && yarn run openapi && PROXY_TARGET=http://localhost:8089 yarn dev'
