observability:
  enabled: true
  exporter:
    endpoint: "http://localhost:4318"
    protocol: "http/protobuf"
  traces:
    sampler: "parent_based_trace_id_ratio"
    samplerArg: 1.0
metricsPort: 9006
postgres:
  connection:
    host: localhost
    port: 5432
    user: postgres
    password: psw
    dbname: scheduler
    sslmode: disable
pulsar:
  URL: "pulsar://localhost:6650"
  restURL: "http://localhost:8090"
  backoffTime: 1s
  maxBackoffTime: 5s
  backoffRandomizationFactor: 0.5
  backoffMultiplier: 1.5
  deadLetterTopic: scheduler-events-dead-letter
  deadLetterMaxAttempts: 5
