source "https://rubygems.org"

# We use the GitHub Pages gem: https://rubygems.org/gems/github-pages
# To upgrade, run `bundle update github-pages`.
# Any plugin listed at https://pages.github.com/versions/ is available for use in your site (no need to add it here).
# Any plugin that's not listed there can't be used.
gem "github-pages", "~> 231", group: :jekyll_plugins

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Requiring this version of webrick permits this to work under ruby 3.x.
gem "webrick", "~> 1.7"
