httpPort: 8082
executorApiConnection:
  armadaUrl: "localhost:50052"
  forceNoTls: true
observability:
  enabled: true
  exporter:
    endpoint: "http://localhost:4318"
    protocol: "http/protobuf"
  traces:
    sampler: "parent_based_trace_id_ratio"
    samplerArg: 1.0
metric:
  port: 9002
kubernetes:
  toleratedTaints:
    - node-tests
  trackedNodeLabels:
    - armadaproject.io/node-pool
application:
  clusterId: "local-cluster"
  pool: "default"
  errorCategories:
    enabled: true
    defaultCategory: uncategorized
    categories:
      - name: oom
        rules:
          - onConditions: ["OOMKilled"]
      - name: user_error
        rules:
          - onExitCodes:
              operator: In
              values: [1, 2, 126, 127]
