name: Release Python Client to PYPI

on:
  workflow_dispatch: {}

jobs:
  run-python-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Setup Go
        uses: ./.github/actions/setup-go-cache
        with:
          cache-prefix: run-python-tests
      - name: Install Protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3
        with:
          version: '23.3'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/workflows/python-tests
        with:
          python-version: '3.10'
          tox-env: 'py310'
          path: 'client/python'
          github-token: ${{secrets.GITHUB_TOKEN}}
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: client/python/dist/
