apiPort: 18089
metricsPort: 19003
corsAllowedOrigins:
  - "http://localhost:3000"
  - "http://localhost:18089"
  - "http://localhost:10000"
  - "http://localhost:18081"
auth:
  anonymousAuth: true
postgres:
  connection:
    host: localhost
    port: 5432
    user: postgres
    password: psw
    dbname: lookout
    sslmode: disable
uiConfig:
  backend: "jsonb"
  armadaApiBaseUrl: "http://localhost:18081"
  binocularsBaseUrlPattern: "http://localhost:18084"
  customTitle: "Armada Local Dev"
  userAnnotationPrefix: "armadaproject.io/"
